# Generated by Django 2.1.5 on 2019-01-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190131_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Calendar', 'verbose_name_plural': 'Calendar'},
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(help_text='Artistname, max 250 chars length', max_length=250),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, help_text='Setlist, etc.', null=True, verbose_name='Show notes'),
        ),
    ]
